/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DATOS;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author fabri
 */
public class frmVentanadePrueba extends javax.swing.JFrame {
 List<Retazo>retazo= new ArrayList<>();
 List<Varilla>varilla= new ArrayList<>();
 
 
    /**
     * Creates new form frmVentanadePrueba
     */
    public frmVentanadePrueba() {
        initComponents();
        DefaultTableModel modeloV = new DefaultTableModel();
        modeloV.addColumn("Nombre");
        modeloV.addColumn("Medida");
        modeloV.addColumn("Grosor");
        modeloV.addColumn("Color");
        modeloV.addColumn("Cantidad");
        tbl_Varilla.setModel(modeloV);
        
        DefaultTableModel modeloR = new DefaultTableModel();
        modeloR.addColumn("Nombre");
        modeloR.addColumn("Medida");
        modeloR.addColumn("Grosor");
        modeloR.addColumn("Color");
        modeloR.addColumn("Cantidad");
        tbl_Retazo.setModel(modeloR);
        
         lbl_cantidad.setVisible(false);
        lbl_medida.setVisible(false);
        txt_cantidad.setVisible(false);
        txt_medagre.setVisible(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Color = new javax.swing.JLabel();
        txt_nomagre = new javax.swing.JTextField();
        txt_groagre = new javax.swing.JTextField();
        txt_colagre = new javax.swing.JTextField();
        rbt_varagre = new javax.swing.JRadioButton();
        rbt_retagre = new javax.swing.JRadioButton();
        lbl_medida = new javax.swing.JLabel();
        txt_medagre = new javax.swing.JTextField();
        btn_Agregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbl_cantidad = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nomcorte = new javax.swing.JTextField();
        txt_grocorte = new javax.swing.JTextField();
        txt_colcorte = new javax.swing.JTextField();
        txt_corte = new javax.swing.JTextField();
        rbt_varcort = new javax.swing.JRadioButton();
        rbt_retcort = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        btn_Actualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rbt_varbus = new javax.swing.JRadioButton();
        rbt_retbus = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        txt_nombrebuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Varilla = new javax.swing.JTable();
        btn_buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Retazo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("AGREGAR"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 40, -1, -1));

        jLabel2.setText("Grosor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 82, -1, -1));

        Color.setText("Color:");
        jPanel1.add(Color, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 124, -1, -1));
        jPanel1.add(txt_nomagre, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 36, 100, -1));
        jPanel1.add(txt_groagre, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 78, 100, -1));
        jPanel1.add(txt_colagre, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 120, 100, -1));

        buttonGroup1.add(rbt_varagre);
        rbt_varagre.setText("Varilla");
        rbt_varagre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_varagreActionPerformed(evt);
            }
        });
        jPanel1.add(rbt_varagre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        buttonGroup1.add(rbt_retagre);
        rbt_retagre.setText("Retazo");
        rbt_retagre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_retagreActionPerformed(evt);
            }
        });
        jPanel1.add(rbt_retagre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        lbl_medida.setText("Medida:");
        jPanel1.add(lbl_medida, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));
        jPanel1.add(txt_medagre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 90, -1));

        btn_Agregar.setText("Agregar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 80, 40));

        jLabel8.setText("Tipo de Aluminio:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        lbl_cantidad.setText("Cantidad:");
        jPanel1.add(lbl_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));
        jPanel1.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 90, -1));
        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jTabbedPane3.addTab("AGREGAR", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("CORTE"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Nombre:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel5.setText("Grosor:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel6.setText("Color:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel7.setText("Corte:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel2.add(txt_nomcorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 80, -1));
        jPanel2.add(txt_grocorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 80, -1));
        jPanel2.add(txt_colcorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 80, -1));
        jPanel2.add(txt_corte, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 80, -1));

        buttonGroup2.add(rbt_varcort);
        rbt_varcort.setText("Varilla");
        jPanel2.add(rbt_varcort, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        buttonGroup2.add(rbt_retcort);
        rbt_retcort.setText("Retazo");
        jPanel2.add(rbt_retcort, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        jLabel9.setText("Tipo de Aluminio:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 100, 40));

        jTabbedPane3.addTab("CORTE", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSQUEDA"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup3.add(rbt_varbus);
        rbt_varbus.setText("Varilla");
        jPanel3.add(rbt_varbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        buttonGroup3.add(rbt_retbus);
        rbt_retbus.setText("Retazo");
        jPanel3.add(rbt_retbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        jLabel10.setText("Nombre:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 50));
        jPanel3.add(txt_nombrebuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 100, 30));

        tbl_Varilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Varilla);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 400, 100));

        btn_buscar.setText("Buscar");
        jPanel3.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 80, 40));

        tbl_Retazo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_Retazo);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, 100));

        jTabbedPane3.addTab("BUSQUEDA", jPanel3);

        getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        DefaultTableModel modeloV=(DefaultTableModel) tbl_Varilla.getModel();
        DefaultTableModel modeloR=(DefaultTableModel) tbl_Retazo.getModel();
        String nombre=txt_nomcorte.getText();
        String grosor=txt_grocorte.getText();
        String color=txt_colcorte.getText();
        if (rbt_varcort.isSelected()) {
             
            double corte=Double.parseDouble(txt_corte.getText());
            Iterator<Varilla> it = varilla.iterator();
            while(it.hasNext()){
                Varilla var=it.next();
                if (var.getNombre().equalsIgnoreCase(nombre) &&
                    var.getGrosor().equalsIgnoreCase(grosor) &&
                    var.getColor().equalsIgnoreCase(color)) {
                    double medida=var.medida-corte;
                    int fila=varilla.indexOf(var);
                    int canti = var.getCantidad()-1;
                    var.setCantidad(canti);
                    modeloV.setValueAt(canti, fila, 4);
                    Retazo R=new Retazo(nombre, medida, grosor, color, 1);
                    retazo.add(R);
                    Object[]Row = new Object[]{
                        R.getNombre(),R.getMedida(),R.getGrosor(),R.getColor(),R.getCantidad()
                    };
                    modeloR.addRow(Row);
                    if (var.getCantidad() < 1) {
                        it.remove();
                    }
                }
            }
            modeloV.setRowCount(0);
            for (Varilla var : varilla) {
                Object[]Row={var.getNombre(),var.medida,var.getGrosor(),var.getColor(),var.getCantidad()};
                modeloV.addRow(Row);
            }
            if (rbt_retcort.isSelected()) {
                double corter=Double.parseDouble(txt_corte.getText());
                Iterator<Retazo> itr = retazo.iterator();
                while (itr.hasNext()) {                    
                    Retazo ret = itr.next();
                    if (ret.getNombre().equalsIgnoreCase(nombre) && 
                            ret.getColor().equalsIgnoreCase(color) &&
                            ret.getGrosor().equalsIgnoreCase(grosor)) {
                        double medida=ret.getMedida()-corter;
                          Retazo R = new Retazo(nombre, medida, grosor, color, 1);
                          retazo.add(R);
                           ret.setCantidad(ret.getCantidad() - 1);
                           if (ret.getCantidad() < 1) {
                           itr.remove();
                        }
                    }
                }
                modeloV.setRowCount(0);
                for (Retazo ret : retazo) {
                    Object[]Row={ret.getNombre(),ret.getMedida(),ret.getGrosor(),ret.getColor(),ret.getCantidad()};
                    modeloR.addRow(Row);
                }
            }
            txt_nomagre.setText("");
            txt_groagre.setText("");
            txt_colagre.setText("");
            txt_cantidad.setText("");
            txt_medagre.setText("");
        }
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
     
        if (rbt_varagre.isSelected()) {
            DefaultTableModel modelo=(DefaultTableModel) tbl_Varilla.getModel();
            String nombre=txt_nomagre.getText();
            String grosor=txt_groagre.getText();
            String color=txt_colagre.getText();
            int cantidad=Integer.parseInt(txt_cantidad.getText());
            Varilla V = new Varilla(nombre, grosor, color, cantidad);
            varilla.add(V);
            Object[]Row = new Object[]{
                V.getNombre(),V.medida,V.getGrosor(),V.getColor(),V.getCantidad()
            };
            modelo.addRow(Row);
        }
        if (rbt_retagre.isSelected()) {
             DefaultTableModel modelo=(DefaultTableModel) tbl_Retazo.getModel();
            double medida=Double.parseDouble(txt_medagre.getText());
            String nombre=txt_nomagre.getText();
            String grosor=txt_groagre.getText();
            String color=txt_colagre.getText();
            int cantidad=1;
            Retazo R=new Retazo(nombre, medida, grosor, color, cantidad);
            retazo.add(R);
            Object[]Row = new Object[]{
                R.getNombre(),R.getMedida(),R.getGrosor(),R.getColor(),R.getCantidad()
            };
            modelo.addRow(Row);
        }
        txt_nomagre.setText("");
        txt_groagre.setText("");
        txt_colagre.setText("");
        txt_cantidad.setText("");
        txt_medagre.setText("");
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void rbt_varagreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_varagreActionPerformed
        lbl_cantidad.setVisible(true);
        lbl_medida.setVisible(false);
        txt_cantidad.setVisible(true);
        txt_medagre.setVisible(false);
    }//GEN-LAST:event_rbt_varagreActionPerformed

    private void rbt_retagreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_retagreActionPerformed
        lbl_cantidad.setVisible(false);
        lbl_medida.setVisible(true);
        txt_cantidad.setVisible(false);
        txt_medagre.setVisible(true);
    }//GEN-LAST:event_rbt_retagreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentanadePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentanadePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentanadePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentanadePrueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVentanadePrueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Color;
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_medida;
    private javax.swing.JRadioButton rbt_retagre;
    private javax.swing.JRadioButton rbt_retbus;
    private javax.swing.JRadioButton rbt_retcort;
    private javax.swing.JRadioButton rbt_varagre;
    private javax.swing.JRadioButton rbt_varbus;
    private javax.swing.JRadioButton rbt_varcort;
    private javax.swing.JTable tbl_Retazo;
    private javax.swing.JTable tbl_Varilla;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_colagre;
    private javax.swing.JTextField txt_colcorte;
    private javax.swing.JTextField txt_corte;
    private javax.swing.JTextField txt_groagre;
    private javax.swing.JTextField txt_grocorte;
    private javax.swing.JTextField txt_medagre;
    private javax.swing.JTextField txt_nomagre;
    private javax.swing.JTextField txt_nombrebuscar;
    private javax.swing.JTextField txt_nomcorte;
    // End of variables declaration//GEN-END:variables
}
